frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\HttpException;

/**
 * Site controller
 */
class SiteController extends Controller {

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
        
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/default/login']);
        }
        
        /*@var currentUser frontend\models\User */
        $currentUser = Yii::$app->user->identity;
        $limit = Yii::$app->params['feedPostLimit'];
        $page = Yii::$app->request->get('page', 1);
        $feedList = $currentUser->getFeed($page, $limit);

        if (Yii::$app->request->isAjax && Yii::$app->request->get('move') == 1) {
            if(!empty($feedList)){
                return $this->renderAjax('_feed', [
                    'feedList' => $feedList,
                    'currentUser' => $currentUser,
                ]);
            } else {
                return false;
            }
        }

        return $this->render('index', [
            'feedList' => $feedList,
            'currentUser' => $currentUser,
        ]);
    }
        
    /**
     * Change language
     */
    public function actionLanguage() {
        /* Принимаем язык выбранный пользователем (post) */
        $language = Yii::$app->request->post('language');

        if(isset($language) && in_array($language, ['en-US', 'ru-RU'])){   
            /* Устанавливаем язык для всего приложения */
            Yii::$app->language = $language;
            /* Создаем Cookie */
            $languageCookie = new Cookie([
                'name' => 'language',
                'value' => $language,
                'expire' => time() + 60 * 60 * 24 *30, //30 days
            ]);
            /* Отправляем Cookie пользователю */
            Yii::$app->response->cookies->add($languageCookie);
            
            /* Возвращаем пользователя на ту же страницу где он находился */
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            Yii::$app->session->setFlash('error', Yii::t('site', 'Sorry, this language does not exist.'));
            /* Возвращаем пользователя на ту же страницу где он находился */
            return $this->redirect(Yii::$app->request->referrer);
            
            //throw new HttpException(400, Yii::t('site', 'Invalid language value.'));
        }  
    }
    
    /**
     * Displays about us.
     *
     * @return mixed
     */
    public function actionAbout() {               
        return $this->render('about');
    }
}

frontend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\bootstrap\Html;
use yii\bootstrap\Nav;
use frontend\assets\AppAsset;
use frontend\assets\FontAwesomeAsset;
use common\widgets\Alert;
use yii\helpers\Url;

AppAsset::register($this);
FontAwesomeAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    
    <body class="home page">
        <?php $this->beginBody() ?>
            <div class="wrapper">
                <header>
                    <div class="header-top">
                        <div class="container">
                            <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4 brand-logo">
                                <h1>
                                    <a href="<?= Url::to(['/site/index']) ?>">
                                        <img src="/img/logo.png" alt="images">
                                    </a>
                                </h1>
                            </div>			
                            <div class="col-md-4 col-sm-4 navicons-topbar">
                                <ul>
                                    <li class="blog-search">
                                        <a href="#" title="Search"><i class="fa fa-search"></i></a>
                                    </li>
                                    <li>
                                        <?= Html::beginForm('/site/language') ?>
                                        <?= Html::dropDownList('language', Yii::$app->language, ['en-US' => 'English', 'ru-RU' => 'Русский'], ['class' => '']) ?>
                                        <?= Html::submitButton('<span class="glyphicon glyphicon-globe"></span>', ['class' => 'btn btn-secondary']) ?>
                                        <?= Html::endForm() ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="header-main-nav">
                        <div class="container">
                            <div class="main-nav-wrapper">
                                <nav class="main-menu">
                                    <?php
                                    if (Yii::$app->user->isGuest) {
                                        $menuItems[] = ['label' => Yii::t('menu', 'About'), 'url' => ['/site/about']];                                        
                                        $menuItems[] = ['label' => Yii::t('menu', 'Signup'), 'url' => ['/user/default/signup']];
                                        $menuItems[] = ['label' => Yii::t('menu', 'Login'), 'url' => ['/user/default/login']];
                                    } else {
                                        $menuItems[] = ['label' => Yii::t('menu', 'Newsfeed'), 'url' => ['/site/index']];
                                        $menuItems[] = ['label' => Yii::t('menu', 'My profile'), 'url' => ['/user/profile/view', 'nickname' => Yii::$app->user->identity->getNickname()]];
                                        $menuItems[] = ['label' => Yii::t('menu', 'Create post'), 'url' => ['/post/default/create']];
                                        $menuItems[] = '<li>'
                                                . Html::beginForm(['/user/default/logout'], 'post')
                                                . Html::submitButton(
                                                    Yii::t('menu', 'Logout ({username})',[
                                                        'username' => Yii::$app->user->identity->username
                                                    ]).'<i class="fa fa-sign-out"></i>', ['class' => 'btn btn-link logout']
                                                )
                                                . Html::endForm()
                                                . '</li>';
                                    }
                                    echo Nav::widget([
                                        'options' => ['class' => 'menu navbar-nav navbar-right'],
                                        'items' => $menuItems,
                                    ]);
                                    ?>
                                </nav>				
                            </div>
                        </div>
                    </div>
                </header>	

                <div class="container full">
                    <?= Alert::widget() ?>
                    <?= $content ?>
                </div>
                
                <div class="push"></div>
            </div>
        
            <footer>                
                <div class="footer">
                    <div class="back-to-top-page">
                        <a class="back-to-top"><i class="fa fa-angle-double-up"></i></a>
                    </div>
                    <p class="text"><a href="<?= Url::to(['/site/about'])?>">Images | 2017</a></p>
                </div>
           </footer>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>